# Generated by Django 5.0.4 on 2024-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=None, max_length=35),
        ),
    ]
